# Generated by Django 3.2.9 on 2021-11-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20211114_2157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_db',
        ),
    ]
