# Generated by Django 3.2.9 on 2021-11-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_contact_contact_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_db',
            name='date',
            field=models.DateField(),
        ),
    ]
