# Generated by Django 3.2.9 on 2021-11-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_contact_db_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_db',
            name='title',
            field=models.CharField(default='Help', max_length=30),
        ),
    ]
