# Generated by Django 3.2.9 on 2021-11-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_apply_license_branches_exam_results_exams_laws_profile_vehicles_view_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='traffic_offences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(max_length=30)),
                ('offence_type', models.CharField(max_length=30)),
                ('due_fine', models.CharField(max_length=30)),
                ('offence_date', models.DateTimeField()),
                ('offence_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='citizenship',
            field=models.CharField(default='1234567890', max_length=30),
        ),
    ]
