# Generated by Django 3.2.9 on 2021-11-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20211116_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view_license',
            old_name='vehicle_type',
            new_name='license_type',
        ),
    ]
