# Generated by Django 3.2.9 on 2021-11-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_rename_vehicle_type_view_license_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view_license',
            name='license_type',
            field=models.CharField(choices=[('Learner', 'Learner'), ('Two-Wheeler', 'Two-Wheeler'), ('Four-Wheeler', 'Four-Wheeler')], max_length=30),
        ),
    ]
