# Generated by Django 3.2.9 on 2021-11-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_view_license_license_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('exam_time', models.DateTimeField()),
                ('exam_type', models.CharField(choices=[('Written', 'Written'), ('Practical', 'Practical')], max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='branches',
            new_name='branch',
        ),
        migrations.RenameModel(
            old_name='exam_results',
            new_name='exam_result',
        ),
        migrations.RenameModel(
            old_name='laws',
            new_name='law',
        ),
        migrations.RenameModel(
            old_name='traffic_offences',
            new_name='traffic_offence',
        ),
        migrations.RenameModel(
            old_name='vehicles',
            new_name='vehicle',
        ),
        migrations.DeleteModel(
            name='exams',
        ),
        migrations.AlterField(
            model_name='apply_license',
            name='vehicle_type',
            field=models.CharField(choices=[('Learner', 'Learner'), ('Two-Wheeler', 'Two-Wheeler'), ('Four-Wheeler', 'Four-Wheeler')], max_length=30),
        ),
    ]
