# Generated by Django 3.2.9 on 2021-11-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20211116_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_time',
            new_name='exam_datetime',
        ),
    ]
