# Generated by Django 3.2.9 on 2021-11-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_rename_exam_time_exam_exam_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
    ]
