# Generated by Django 3.2.9 on 2021-11-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_auto_20211116_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_licenses_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('citizenship', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(choices=[('Learner', 'Learner'), ('Two-Wheeler', 'Two-Wheeler'), ('Four-Wheeler', 'Four-Wheeler')], max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('application_date', models.DateTimeField()),
                ('applicant_email', models.CharField(max_length=30)),
                ('license_type', models.CharField(max_length=30)),
                ('exam_datetime', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='apply_license_db',
        ),
    ]
