# Generated by Django 3.2.9 on 2021-11-17 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_auto_20211116_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_db',
            name='exam_datetime',
        ),
        migrations.AddField(
            model_name='exam_db',
            name='exam_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='exam_db',
            name='exam_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
