# Generated by Django 3.2.9 on 2021-11-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_exam_db_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic_offence_db',
            name='officer_name',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
