# Generated by Django 3.2.9 on 2021-11-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_traffic_offence_db_officer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic_offence_db',
            name='fee_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=30),
        ),
    ]
