# Generated by Django 3.2.9 on 2021-11-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_remove_apply_licenses_db_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_licenses_db',
            name='username',
        ),
    ]
